stages:
- stage: Provision
  jobs:
  - job:
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'MyAzureServiceConnection'
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
-
    

   
'az group create --name $(environmentName) --location westeurope;':
az vm create `
        --name ProvisionedVM `
        --image Win2019Datacenter `
        --admin-password "$(adminPassword)"`
        --resource-group $(environmentName)